spring:
  ai:
    vertex:
      ai:
        gemini:
          projectId: ${GEMINI_PROJECT_ID}
          location: ${GEMINI_LOCATION}
  application:
    name: gem-api

#firebase:
#  databaseUrl: ${FIREBASE_DATABASE_URL}
