spring:
  ai:
    vertex:
      ai:
        gemini:
          projectId: ${GEMINI_PROJECT_ID}
          location: ${GEMINI_LOCATION}
  application:
    name: gem-api

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
logging:
  level:
    root: debug
